name: dartling_default_app
version: 2.0.2
author: Dzenan Ridjanovic <dzenanr@gmail.com>
description: dartling default app is used to interpret a dartling model and provide a web app to navigate through the model starting by its entry points
homepage: https://github.com/dzenanr/dartling_default_app
documentation: http://goo.gl/Fd08zZ
environment:
  sdk: '>=1.10.0 <2.0.0'
dependencies:
  browser: ^0.10.0+2 
  dartling: ^2.0.2
  intl: ^0.12.2+1 
