name: dartling_default_app
version: 1.0.0
author: Dzenan Ridjanovic <dzenanr@gmail.com>
description: dartling default app is used to interpret a dartling model and provide a web app to navigate through the model starting by its entry points
homepage: http://ondart.me/
documentation: http://goo.gl/Fd08zZ
environment:
  sdk: '>=0.8.10+8 <2.0.0'
dependencies:
  browser: '>=0.9.0 <0.10.0'
  dartling: '>=1.0.0 <2.0.0'
  intl: '>=0.9.0 <0.10.0'
